import json
from pathlib import Path

from src.libs.loader.loader_factory import LoaderFactory
from src.libs.loader.mineru_loader import MinerULoader


def test_loader_factory_uses_mineru_for_pdf():
    loader = LoaderFactory.create("example.pdf")

    assert isinstance(loader, MinerULoader)


def test_mineru_loader_reads_markdown_content_list_and_images(tmp_path, monkeypatch):
    pdf_path = tmp_path / "lesson.pdf"
    pdf_path.write_bytes(b"%PDF-1.4\n%%EOF")

    output_root = tmp_path / "mineru"
    image_root = tmp_path / "images"
    loader = MinerULoader(
        image_storage_dir=image_root,
        mineru_output_root=output_root,
        fallback_to_legacy=False,
    )

    doc_hash = loader._compute_file_hash(pdf_path)
    output_dir = output_root / doc_hash
    output_dir.mkdir(parents=True)
    (output_dir / "lesson.md").write_text(
        "# Lesson\n\nThis is parsed by MinerU.\n\n![chart](images/chart.png)",
        encoding="utf-8",
    )
    image_dir = output_dir / "images"
    image_dir.mkdir()
    source_image = image_dir / "chart.png"
    source_image.write_bytes(b"fake-png")
    (output_dir / "lesson_content_list.json").write_text(
        json.dumps(
            [
                {"type": "text", "text": "This is parsed by MinerU.", "page_idx": 0},
                {
                    "type": "image",
                    "img_path": "images/chart.png",
                    "caption": "A chart generated by MinerU",
                    "page_idx": 0,
                },
            ],
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    monkeypatch.setattr(MinerULoader, "_run_mineru", lambda self, path, out: "mineru")

    document = loader.load(pdf_path)

    assert document.text.startswith("# Lesson")
    assert document.metadata["parser"] == "mineru"
    assert document.metadata["page_count"] == 1
    assert document.metadata["title"] == "Lesson"
    assert len(document.metadata["images"]) == 1
    image_metadata = document.metadata["images"][0]
    assert image_metadata["page"] == 1
    assert image_metadata["caption"] == "A chart generated by MinerU"
    assert Path(image_metadata["path"]).exists()
    assert Path(image_metadata["path"]).parent == image_root / doc_hash
